server:
  port: 8002
spring:
  application:
    name: regist-center
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server0:8000/eureka/,http://server1:8001/eureka/
  instance:
    hostname: server2


