server:
  port: 8001
spring:
  application:
    name: regist-center
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server0:8000/eureka/,http://server2:8002/eureka/
  instance:
    hostname: server1


